---
format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
app:
  envs:
    - TEST_SHARD_COUNT: 2
    - PROJECT_LOCATION: "./"
      opts:
        is_expand: false
    - MODULE: app
      opts:
        is_expand: false
pipelines:
  run_tests:
    workflows:
      run_instrumented_tests:
        parallel: "$TEST_SHARD_COUNT"
workflows:
  entry_distribute_dev:
    summary: Run your Android unit tests and create an APK file to install your app
      on a device or share it with your team.
    description: The workflow will first clone your Git repository, install Android
      tools, set the project's version code based on the build number, run
      Android lint and unit tests, build the project's APK file and save it.
    steps:
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - activate-build-cache-for-gradle:
      - set-java-version@1:
          inputs:
            - set_java_version: '21'
      - install-missing-android-tools@3:
          inputs:
            - gradlew_path: "$PROJECT_LOCATION/gradlew"
      - change-android-versioncode-and-versionname@1:
          inputs:
            - build_gradle_path: "$PROJECT_LOCATION/$MODULE/build.gradle.kts"
      - gradle-runner@3:
          title: Run ktlintCheck
          inputs:
            - gradle_task: lintKotlin
            - gradle_options: "--no-daemon"
            - gradlew_path: "./gradlew"
      - android-unit-test@1:
          inputs:
            - project_location: "$PROJECT_LOCATION"
            - variant: "$VARIANT"
            - cache_level: none
      - android-build@1:
          inputs:
            - project_location: "$PROJECT_LOCATION"
            - module: "$MODULE"
            - variant: "$VARIANT"
            - cache_level: none
            - build_type: aab
      - android-build@1:
          inputs:
            - project_location: "$PROJECT_LOCATION"
            - module: "$MODULE"
            - variant: "$VARIANT"
      - sign-apk@2:
          run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
          inputs:
            - android_app: "$BITRISE_AAB_PATH"
      - sign-apk@2:
          inputs:
            - android_app: "$BITRISE_APK_PATH"
      - deploy-to-bitrise-io@2: {}
      - firebase-app-distribution@0:
          inputs:
            - app: 1:245899623921:android:8c082deb52f8807d6ad850
            - firebase_token: "$FIREBASE_TOKEN"
            - release_notes_file: ''
            - release_notes: "Branch: $BITRISE_GIT_BRANCH\ 

            $BITRISE_GIT_MESSAGE\ 


            $APP_BUILD_DESCRIPTION"
            - release_notes_length: '400'
            - app_path: "$BITRISE_APK_PATH"
    envs:
      - VARIANT: debug
        opts:
          is_expand: false
  run_instrumented_tests:
    summary: Run your Android instrumented tests and get the test report.
    description: The workflow will first clone your Git repository, cache your
      Gradle dependencies, install Android tools, run your Android instrumented
      tests and save the test report.
    steps:
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - restore-gradle-cache@2: {}
      - install-missing-android-tools@3:
          inputs:
            - gradlew_path: "$PROJECT_LOCATION/gradlew"
      - avd-manager@2: {}
      - wait-for-android-emulator@1: {}
      - gradle-runner@3:
          inputs:
            - gradlew_path: "$PROJECT_LOCATION/gradlew"
            - gradle_task: |-
                connectedAndroidTest \
                  -Pandroid.testInstrumentationRunnerArguments.numShards=$BITRISE_IO_PARALLEL_TOTAL \
                  -Pandroid.testInstrumentationRunnerArguments.shardIndex=$BITRISE_IO_PARALLEL_INDEX
      - save-gradle-cache@1: {}
      - deploy-to-bitrise-io@2: {}
  run_tests:
    summary: Run your Android unit tests and get the test report.
    description: The workflow will first clone your Git repository, cache your
      Gradle dependencies, install Android tools, run your Android unit tests
      and save the test report.
    steps:
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - restore-gradle-cache@2: {}
      - install-missing-android-tools@3:
          inputs:
            - gradlew_path: "$PROJECT_LOCATION/gradlew"
      - android-unit-test@1:
          inputs:
            - project_location: "$PROJECT_LOCATION"
            - variant: "$VARIANT"
            - cache_level: none
      - save-gradle-cache@1: {}
      - deploy-to-bitrise-io@2: {}
    triggers:
      push:
        - branch: main
      pull_request:
        - source_branch: "*"
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
